services:
  - type: web
    name: rust-datastar-mp
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        sync: false
      - key: RUST_LOG
        value: info
    autoDeploy: true
